# https://docs.travis-ci.com/user/languages/csharp/
language: csharp
mono: none
dotnet: 2.1

branches:
  only:
    - master

install:
  - dotnet restore

script:
  - dotnet build

deploy:
  skip_cleanup: true
  script: serverless deploy
